### ISSUE TITLE
Optional Location Problem

### ISSUE THREAD

**Issue by emanuelduss** [SpaceApi/schema#119]
Hi

As discussed with @rnestler :smiley: 

We have the following definition for our space:
```json
{
  "api_compatibility": ["15"],
  "space": "LuXeria",
  "logo": "https://luxeria.ch/img/luxeria.png",
  "url": "https://luxeria.ch/",
  "contact": {
    "email": "vorstand@luxeria.ch",
    "irc": "https://t.me/luxeria_irc",
    "twitter": "@LuXeria_Luzern"
  },
  "issue_report_channels": [
    "email"
  ],
  "state": {
    "message": "The weekly meeting takes place every Wednesday from approx. 20:00 in the following Jitsi meeting room: https://meet.luxeria.ch/LuxeriaTreffen"
  },
  "feeds": {
    "wiki": {
      "type": "rss",
      "url": "https://wiki.luxeria.ch/feed.php"
    }
  },
  "projects": [
    "https://wiki.luxeria.ch/",
    "https://github.com/luxeria"
  ]
}
```

According to the spec, the location is optional:

> May be omitted for spaces without a fixed physical location.

But I get the following error on the validator:

![image](https://github.com/user-attachments/assets/64c18c54-1acc-4989-b862-985a0bd4b5e9)

Validator response:

```json
{"valid":false,"message":"(root): location is required\n","checkedVersions":["15"],"validatedJson"[...]
```

THX,
Mänu

**Comment by dbrgn** [comment]
The validator does not support v15 yet, but - due to a bug - does not indicate the missing version support. Fix is in progress.

**Comment by dbrgn** [comment]
Ah, wrong, the validator _does_ support v15, but a non-final version of the schema 😕 That sounds like a bad idea, in the future we should probably not add intermediate versions to the validator.

Your file validates when running the validator with the latest git version of `go-spaceapi-validator`. We'll have to get that released 🙂

**Comment by rnestler** [comment]
> That sounds like a bad idea, in the future we should probably not add intermediate versions to the validator.

Or only with `15-draft` as the key.

**Comment by dbrgn** [comment]
Your endpoint validates now!

![screenshot-20241231-130450](https://github.com/user-attachments/assets/6eb1f51c-694c-4e20-9bcd-74891e98b74c)

The warning is a mistake now that the location is optional, but we can fix that later. You can ignore it for now.

**Comment by emanuelduss** [comment]
Nice, THX Danilo!
