### ISSUE TITLE
API documentation v0.13 for longitude

### ISSUE THREAD

**Issue by es-ka** [SpaceApi/schema#17]
The [API docs](https://spacedirectory.org/pages/docs.html) for `location/lon` is:
> Use positive values for locations west of Greenwich, and negative values for locations east of Greenwich.

It should be vice versa like +13.0° for eastern longitude.
Otherwise locations of [FIXME](https://fixme.ch/cgi-bin/spaceapi.py) and [coredump](http://status.crdmp.ch/) could be wrong ;-)

**Comment by dbrgn** [comment]
Nice catch! :)
