### ISSUE TITLE
Multiple contact possibilities

### ISSUE THREAD

**Issue by the-metalgamer** [SpaceApi/schema#30]
Hey,

Currently the spaceapi only supports one value for each contact item.

Wouldn't it be better to support multiple values. For examples a space might have multiple phone numbers or it might have multiple twitter/mastodon accounts.

Cheers,
metalgamer

**Comment by dbrgn** [comment]
Can you give a few concrete examples of spaces that have more than one account per type?

**Comment by dbrgn** [comment]
Might, yes. But do you have an actual situation where that is the case? Also, if the door has its own Mastodon account, should that *really* be listed under "contact"? :slightly_smiling_face:

**Comment by the-metalgamer** [comment]
Well, we have in our space 3 Mastodon Accounts and 2 Twitter accounts. On mastodon, we have one account for the organisations which runs the space ("Chaos Computer Club Luxembourg", where we post general stuff, like that we did have a press release etc...), one for the space itself ("ChaosStuff", where we post stuff running in the space (e.g. Events, Projects etc...) and one for the space status.

Currently we have one phone number, which is mobile phone, but in future we will very probably have a landline phone in the space.

For mail addresses, we have 2 main contact possibilities,  info@c3l.lu for general enquiries and one especially for the press!

Personally I think yes, because it is a possibility the get in contact with the space, as you would know when the space is open and can go there.

**Comment by rnestler** [comment]
Maybe we should just have a a generic links sections, something like:
```json
{
"links": [
 { "name": "Door Twitter", "description": "The Twitter account which tweets our door open status", "url": "https://twitter.com/foo/bar" }
]
}
```

**Comment by dbrgn** [comment]
> Maybe we should just have a a generic links sections, something like

I created a PR for this: #67.

**Comment by the-metalgamer** [comment]
I close the issue as the links section was merged some time ago.
