### ISSUE TITLE
Streams

### ISSUE THREAD

**Issue by dbrgn** [SpaceApi/schema#51]
Very similar to #50:

- There is a mix between stream formats (like "mjpeg") and a service that seems a bit out-of-place ("ustream"). Ustream is dead, by the way.
- Shouldn't `m4` be `mp4`? How is this being used in practice?
- Only one stream can be defined per format, and there is no description. We should probably transition to a list of objects with a `format` key and a `description` field.

**Comment by gidsi** [comment]
Will be fixed by #70
