### ISSUE TITLE
Update to new JSON Schema version

### ISSUE THREAD

**Issue by gidsi** [SpaceApi/schema#59]
New specification is out!

New version is `2019-09`, you can find it here:
https://json-schema.org/specification.html

**Comment by gidsi** [comment]
We should wait a bit, there is just one library so far supporting the new draft and that's written in .NET.

[I've asked](https://github.com/xeipuuv/gojsonschema/issues/289) about implementing the new draft in the repo the validator is using.

**Comment by rnestler** [comment]
So let's close it for now and reopen it or open a new one, once implementations support it more broadly.
