### ISSUE TITLE
Release 0.14

### ISSUE THREAD

**Issue by rnestler** [SpaceApi/schema#65]
Tracking issue for releasing 0.14 to the public.

Todos as discussed in the core meeting

 - [x] Add migration guide
 - [x] Explain how to be compatible with 0.13 and 0.14
 - [x] Cleanup CHANGELOG.md (https://github.com/SpaceApi/schema/pull/69)
 - [na] ~~Make the MyHackerspace app compatible~~ (let's not delay the specs release with the app update)
 - [x] Take a look at open issues
   - https://github.com/SpaceApi/schema/pull/71 -> Postponed to v15
   - https://github.com/SpaceApi/schema/pull/58 -> replaced by https://github.com/SpaceApi/schema/pull/80

**Comment by dbrgn** [comment]
Also:

- [ ] Update versioning schema (next version will be v14, not v0.14)
