### ISSUE TITLE
Country code

### ISSUE THREAD

**Issue by dbrgn** [SpaceApi/schema#74]
Sometimes seeing the country code of a space might be useful. For example:

- Knowing in which part of the world a space is: "Garoa Hacker Clube" is loated at -23.564968, -46.69918. Quick, without entering the coordinates into a mapping system, where in the world is it? Coordinates are nice, but sometimes it would be useful to see right away that this space is located in Brazil.
- Namespacing: There are two spaces with similar name and you're not sure which is which, so by looking at the country code you immediately know which region they belong to
- Filtering: You'd like to know what other spaces there are in your country or in the country you're currently visiting. (Note: This can also be done based on distance using the coordinates, but it's more complex to calculate. The country definitely doesn't replace "spaces within 100km of you" though, especially when you live close to the boarder.)

Downsides:

- It's somewhat redundant information (but on the other hand lat/lon reverse lookup to find a country can be a bit complicated and requires an API or a big local geodatabase)
- Some people might object due to political reasons (since boarders and country names should not matter and are a sign of a nationalistic way of thinking which should be avoided?). I do not share that view though.

Any opinions on adding an optional ISO 3166 ALPHA-2 country code to the "location" field in the schema? Useful? Redundant and useless? A symptom of conservative nationalistic opressive patriarchy?

**Comment by dbrgn** [comment]
A note regarding alpha-2 vs alpha-3: ISO-3166 recommends alpha-2 as the general-purpose code. https://www.iso.org/iso-3166-country-codes.html

**Comment by s3lph** [comment]
I don't really see a use case for it. All the scenarios you describe are "human user consumes the country code", which IMO is already covered by the address field, where the large majority of endpoints already put the country.

**Comment by dbrgn** [comment]
One use case: Filter spaces by country without having to do geo-reverse-lookup of the coordinates.

Another use case: Show country flag next to space in MyHackerspace.
