### ISSUE TITLE
Validate schema fails

### ISSUE THREAD

**Issue by gidsi** [SpaceApi/schema#76]
Somethings is wrong with our schema validation.

I've opened #73 and the schema validation went through, after squash merge it into b23285d it now reports `error:  Unexpected token ':'` (regardless if `--errors` is set to `json` or `text`). 

I get the same problem locally, but can't figure out whats wrong, the error message is very generic and i can't figure out a way to make the output more verbose. 

Our schema and the downloaded draft-07 are both valid according to ECMA-404, RFC 4627, RFC 7159 and RFC 8259 (so i'm pretty sure there is no colon where it shouldn't be).

Error can be found [here](https://github.com/SpaceApi/schema/actions/runs/124049261).

**Comment by rnestler** [comment]
Upstream report: https://github.com/ajv-validator/ajv-cli/issues/77

**Comment by gidsi** [comment]
Fixed in #81
