### ISSUE TITLE
Add extra `location` details

### ISSUE THREAD

**Issue by xopr** [SpaceApi/schema#94]
Some spaces occupy a room in a shared building and need a bit more details apart from the postal address or location in general (for example, vertical offset is currently not taken into account)

My suggestion would be to add the following two (optional) fields:
* `floor`: possibly integer; it might need consensus on how numbering is applied, i.e.: in most European countries we start counting at `0` (ground floor)
* `room`: string; a dedicated room "number" as provided by the building manager, in the case of ACKspace, it's `L406` from wing/section "L", floor "4" and door "6" as provided per building.

An example would look like this:
```
    "location": {
        "address": "Kloosterweg 1, 6412 CN Heerlen",
        "lat": 50.8924622,
        "lon": 5.9712601,
        "timezone": "Europe/Amsterdam",
        "floor": 4,
        "room": "L406"
    },
```

**Comment by the-metalgamer** [comment]
I would personally prefer a simple free-form string called description, which could describe how to find the rooms.

Secondly, maybe one space has multiple floors or multiple rooms, which would be difficult to describe with this. Or maybe a space has special things, like press the doorbell marked with XXX etc... All this could be more easily described in a free form string.

**Comment by dbrgn** [comment]
I concur with @the-metalgamer, a free-form field would be more flexible, and I don't expect tools to specially parse and understand floors and rooms. There are a lot of spaces that are somewhat hidden in a building, and need additional description to find.

My suggestion would be a string field named "description" with the description "If your space is not trivial to find when standing at the address, explain how to get there". Suggestion for other description texts would be welcome.

**Comment by xopr** [comment]
Sure, `description` sounds perfect :+1: 
It might need some guidance on best practices in de API description, but it's a good start.
